# Generated by Django 3.2.9 on 2021-11-16 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\d+{3,20}$')])),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
            ],
        ),
    ]
