# Generated by Django 3.2.9 on 2021-11-17 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='invalid phone format', regex='^\\d{3,20}$')]),
        ),
    ]
